services:
  db:
    image: postgres:17-alpine
    container_name: postgres_dev
    restart: always
    env_file:
      - ./server/.env
    environment:
      - POSTGRES_USER=${POSTGRES_USER}
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD}
      - POSTGRES_DB=${POSTGRES_DB}
    ports:
      - "${POSTGRES_PORT}:5432"
    volumes:
      - db_data_dev:/var/lib/postgresql/data
    networks:
      - app-network

volumes:
  db_data_dev:

networks:
  app-network:
    driver: bridge