services:
  client:
    build:
      context: ./client
      dockerfile: Dockerfile
    env_file:
      - ./client/.env
    ports:
      - "5173:5173"
    volumes:
      - ./client/src:/app/src
      - ./client/public:/app/public
      - /app/node_modules
    depends_on:
      - server
    networks:
      - app-network

  server:
    container_name: server_${NODE_ENV}
    ports:
      - "3000:3000"
    build:
      context: ./server
      dockerfile: Dockerfile
    env_file:
      - ./server/.env.${NODE_ENV}
    depends_on:
      - db
      # - redis
    networks:
      - app-network

  db:
    image: postgres:17-alpine
    container_name: postgres_${NODE_ENV}
    restart: always
    env_file:
      - ./server/.env.${NODE_ENV}
    ports:
      - ${POSTGRES_PORT}:5432
    volumes:
      - db_data_${NODE_ENV}:/var/lib/postgresql/data
    networks:
      - app-network
volumes:
  db_data_development:
  db_data_test:
  db_data_production:

networks:
  app-network:
    driver: bridge
